# Generated by Django 3.0.4 on 2020-04-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTestManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='dataFormat',
            field=models.CharField(max_length=30, null=True, verbose_name='服务器返回的数据格式'),
        ),
    ]
