# Generated by Django 3.0.4 on 2020-04-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200414_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='is_sign',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sign',
        ),
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
